#!/bin/bash
set -e
export APP="$1"
export CONTAINER="app/$APP"
export PLUGIN_PATH=$HOME/plugins

pluginhook pre-build

echo "-----> Building $APP ..."
cat | $HOME/buildstep $CONTAINER
echo "-----> Build complete!"

pluginhook post-build

pluginhook pre-deploy

echo "-----> Deploying $APP ..."
$HOME/deploystep $APP $CONTAINER
echo

pluginhook post-deploy

fi