#!/bin/bash
set -e
APP="$1"
CONTAINER="app/$APP"
export PLUGIN_PATH=$HOME/plugins

# Retain app payload from stdin while other I/O may potentially occur
TEMP_PAYLOAD=$(mktemp /tmp/dokku_payload.XXXXXX)
cat > $TEMP_PAYLOAD

pluginhook pre-build $APP $CONTAINER

echo "-----> Building $APP ..."
$HOME/buildstep $CONTAINER < $TEMP_PAYLOAD
echo "-----> Build complete!"

pluginhook post-build $APP $CONTAINER

pluginhook pre-deploy $APP $CONTAINER

echo "-----> Deploying $APP ..."
$HOME/deploystep $APP $CONTAINER
echo

pluginhook post-deploy $APP $CONTAINER